services:
  - type: web
    name: genai-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    contextPath: AiInterTask/backend
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: genai-frontend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    contextPath: AiInterTask/frontend
    envVars:
      - key: BACKEND_URL
        value: https://wasserstoff-5-sv55.onrender.com/
      - key: PORT
        value: 8501
